import { initAccounts } from './profiles.js?v=appearance-library-1';
import { summarize } from './pitch.js';
import { routines, buildRoutine } from './routines.js';
import { readState, writeState, clearState, clipStore } from './storage.js';
const $=id=>document.getElementById(id);
let storageOwner='guest',accounts;const ownerKey=key=>storageOwner==='guest'?key:`${key}:${storageOwner}`;
const local={getItem:key=>window.localStorage.getItem(ownerKey(key)),setItem:(key,value)=>window.localStorage.setItem(ownerKey(key),value),removeItem:key=>window.localStorage.removeItem(ownerKey(key))};
let state=readState(local), stream=null, context=null, source=null, analyser=null, worker=null;
let captureTimer=null, busy=false, connecting=false, generation=0, history=[], smooth=[], recorder=null, recordingStart=0, recordingTimer=null;
let draft=null, draftURL=null, clipURLs=[], session=null, review=null, sessionTimer=null, previousTick=0;
const time=n=>`${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,'0')}`;
function notify(message,error=false){$('notice').textContent=message;$('notice').classList.toggle('error',error);$('notice').hidden=false;}
function persist(){try{writeState(local,state);accounts?.changed();return true;}catch{notify('Browser storage is unavailable or full. Changes are temporary; export your progress before leaving.',true);return false;}}
function el(tag,text,className){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(className)node.className=className;return node;}
function download(blob,name){const url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function clipExtension(blob){return blob.type.includes('mp4')?'m4a':blob.type.includes('ogg')?'ogg':'webm';}
function ask(title,copy,action){$('confirm-title').textContent=title;$('confirm-copy').textContent=copy;$('confirm-ok').onclick=async()=>{$('confirm-dialog').close();try{await action();}catch{notify('Could not complete the deletion. Please try again.',true);}};$('confirm-dialog').showModal();$('confirm-cancel').focus();}
$('confirm-cancel').onclick=()=>$('confirm-dialog').close();
function route(){const name=location.hash.slice(1)||'studio',known=['studio','practice','recordings','progress','account','care'],active=known.includes(name)?name:'studio';for(const id of known)$(id).hidden=id!==active;document.querySelectorAll('nav a').forEach(a=>{if(a.hash===`#${active}`)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});if(active==='recordings')renderClips();if(active==='progress')renderProgress();if(active==='studio')drawChart();}
window.addEventListener('hashchange',()=>{route();$('main').focus({preventScroll:true});});
$('range-low').value=state.settings.low;$('range-high').value=state.settings.high;$('show-range').checked=state.settings.show;
$('range-form').onsubmit=e=>{e.preventDefault();const low=Number($('range-low').value),high=Number($('range-high').value);if(!Number.isInteger(low)||!Number.isInteger(high)||low<65||high>650||low>=high){notify('Choose whole-number limits from 65–650 Hz, with the lower limit below the upper limit.',true);return;}state.settings={low,high,show:$('show-range').checked};const saved=persist();drawChart();if(saved)notify('Your optional range has been updated. Comfort still comes first.');};
$('show-range').onchange=()=>{state.settings.show=$('show-range').checked;persist();drawChart();};
function drawChart(){const canvas=$('pitch-chart');if($('studio').hidden)return;const rect=canvas.getBoundingClientRect();if(!rect.width)return;const scale=window.devicePixelRatio||1;canvas.width=Math.round(rect.width*scale);canvas.height=Math.round(rect.height*scale);const c=canvas.getContext('2d');c.scale(scale,scale);const w=rect.width,h=rect.height,left=36,top=14,bottom=h-27,right=w-12,now=performance.now();const y=f=>bottom-(Math.log2(f/65)/Math.log2(650/65))*(bottom-top);const palette=getComputedStyle(document.documentElement),color=name=>palette.getPropertyValue(name).trim();c.font='10px system-ui';c.fillStyle=color('--chart-ink');c.strokeStyle=color('--chart-line');for(const f of [80,120,180,260,400,600]){const yy=y(f);c.beginPath();c.moveTo(left,yy);c.lineTo(right,yy);c.stroke();c.fillText(f,3,yy+3);}if(state.settings.show){c.fillStyle=color('--chart-band');c.fillRect(left,y(state.settings.high),right-left,y(state.settings.low)-y(state.settings.high));c.strokeStyle=color('--chart-ink');c.lineWidth=1.5;c.setLineDash([6,4]);for(const f of [state.settings.low,state.settings.high]){c.beginPath();c.moveTo(left,y(f));c.lineTo(right,y(f));c.stroke();}c.setLineDash([]);}c.fillStyle=color('--chart-ink');c.fillText('−30s',left,h-8);c.fillText('now',right-22,h-8);c.strokeStyle=color('--chart-stroke');c.lineWidth=2;c.lineJoin='round';c.beginPath();let drawing=false,last=0;for(const point of history){if(point.t<now-30000)continue;const x=left+(point.t-(now-30000))/30000*(right-left);if(!point.hz){drawing=false;continue;}if(!drawing||point.t-last>250)c.moveTo(x,y(point.hz));else c.lineTo(x,y(point.hz));drawing=true;last=point.t;}c.stroke();}
window.addEventListener('voice-theme-change',drawChart);
new ResizeObserver(drawChart).observe($('pitch-chart'));
function receivePitch(result){busy=false;if(!stream)return;const now=performance.now();let hz=result.hz;if(hz){smooth.push(hz);smooth=smooth.slice(-3);hz=summarize(smooth).median;}else smooth=[];history.push({t:now,hz});history=history.filter(x=>x.t>=now-30000);$('pitch-value').textContent=hz?Math.round(hz):'—';$('pitch-caption').textContent=hz?'Estimated fundamental frequency (F0)':'No clear voiced sound — try easy speech';$('level').value=Math.min(1,result.rms*5);$('signal').textContent=result.peak>.98?'Input clipping — move farther away':hz?'Voiced sound detected':result.rms<.008?'Quiet / silence':'Uncertain signal';if(session&&!session.paused&&hz){session.pitch.push(hz);if(session.pitch.length>7200)session.pitch.shift();}const s=summarize(history.map(x=>x.hz));$('pitch-summary').textContent=s?`Last 30s: median ${Math.round(s.median)} Hz · typical range ${Math.round(s.low)}–${Math.round(s.high)} Hz. Gaps mean silence or uncertainty.`:'No voiced samples yet. Silence and uncertain sound leave gaps.';drawChart();}
function setMicUI(){const on=!!stream; $('header-stop').hidden=!on&&!connecting; $('privacy-status').hidden=on||connecting; $('header-stop').textContent=connecting?'Cancel microphone request':'● Disconnect microphone';$('mic-toggle').textContent=connecting?'Cancel connection':on?'Disconnect microphone':'Connect microphone';$('mic-badge').textContent=connecting?'Awaiting permission':on?'Microphone live':'Microphone off';$('mic-badge').classList.toggle('live',on);$('record-toggle').disabled=!on||!window.MediaRecorder;$('record-toggle').textContent=recorder?.state==='recording'?'■ Stop recording':'● Record a clip';}
async function disconnect(){generation++;connecting=false;clearInterval(captureTimer);captureTimer=null;stopRecording();if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;if(source){source.disconnect();source=null;}const old=context;context=null;worker?.terminate();worker=null;analyser=null;busy=false;smooth=[];$('pitch-value').textContent='—';$('pitch-caption').textContent='Microphone disconnected';$('level').value=0;$('signal').textContent='Microphone off';setMicUI();if(old)await old.close().catch(()=>{});}
async function connect(){if(stream||connecting){await disconnect();return;}if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia){notify('Microphone access needs HTTPS or localhost and a browser with microphone support. You can still use guided practice.',true);return;}const token=++generation;connecting=true;setMicUI();let acquired=null;try{const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)throw new Error('Audio analysis is not supported in this browser.');context=new AudioContext();await context.resume();if(token!==generation)return;acquired=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false},video:false});if(token!==generation||document.hidden){acquired.getTracks().forEach(t=>t.stop());return;}stream=acquired;source=context.createMediaStreamSource(stream);analyser=context.createAnalyser();analyser.fftSize=4096;source.connect(analyser);worker=new Worker(new URL('./pitch-worker.js',import.meta.url),{type:'module'});worker.onmessage=e=>receivePitch(e.data);worker.onerror=()=>{notify('Pitch analysis could not start. Reload the app or try a current browser.',true);disconnect();};stream.getAudioTracks()[0].onended=()=>{notify('Microphone access ended. Reconnect when you are ready.');disconnect();};captureTimer=setInterval(()=>{if(busy||!analyser)return;const samples=new Float32Array(analyser.fftSize);analyser.getFloatTimeDomainData(samples);busy=true;worker.postMessage({buffer:samples.buffer,sampleRate:context.sampleRate},[samples.buffer]);},80);notify(window.MediaRecorder?'Microphone connected. Audio is processed locally; recording starts only when you choose it.':'Pitch is ready. Recording is not supported by this browser.');}catch(e){acquired?.getTracks().forEach(t=>t.stop());if(token===generation){await disconnect();const messages={NotAllowedError:'Microphone permission was denied. Allow it in browser site settings, then try again.',NotFoundError:'No microphone was found. Connect one and try again.',NotReadableError:'The microphone could not be opened. Check system permissions and close other audio apps.'};notify(messages[e.name]||e.message||'Could not connect your microphone.',true);}}finally{if(token===generation){connecting=false;setMicUI();}}}
$('mic-toggle').onclick=connect;
$('header-stop').onclick=disconnect;
$('clear-chart').onclick=()=>{history=[];smooth=[];$('pitch-summary').textContent='History cleared. New voiced samples will appear here.';drawChart();};
function stopRecording(){clearInterval(recordingTimer);recordingTimer=null;if(recorder&&recorder.state!=='inactive')recorder.stop();}
function discardDraft(){if(draftURL)URL.revokeObjectURL(draftURL);draftURL=null;draft=null;$('draft-audio').removeAttribute('src');$('draft-audio').load();$('clip-draft').hidden=true;}
function startRecording(){if(!stream||!window.MediaRecorder)return;if(recorder?.state==='recording'){stopRecording();return;}if(recorder){notify('Please wait for the current clip to finish.');return;}if(draft){notify('Save, download, or discard your temporary clip before recording another.');location.hash='recordings';return;}document.querySelectorAll('audio').forEach(a=>a.pause());try{const type=['audio/webm;codecs=opus','audio/mp4','audio/ogg;codecs=opus','audio/webm'].find(t=>MediaRecorder.isTypeSupported(t));recorder=type?new MediaRecorder(stream,{mimeType:type}):new MediaRecorder(stream);const current=recorder,chunks=[];recordingStart=performance.now();current.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};current.onerror=()=>{notify('Recording encountered an error. Try reconnecting your microphone.',true);stopRecording();};current.onstop=()=>{clearInterval(recordingTimer);recordingTimer=null;const blob=new Blob(chunks,{type:current.mimeType||chunks[0]?.type||'audio/webm'});recorder=null;setMicUI();if(!blob.size){notify('No audio was captured. Please try again.',true);return;}draft={id:crypto.randomUUID(),blob,date:new Date().toISOString(),duration:Math.min(120,(performance.now()-recordingStart)/1000),name:''};draftURL=URL.createObjectURL(blob);$('draft-audio').src=draftURL;$('clip-name').value='';$('clip-draft').hidden=false;notify('Your clip is ready in Recordings. Save it locally or download a copy.');if(!document.hidden)location.hash='recordings';};current.start(1000);recordingTimer=setInterval(()=>{const seconds=(performance.now()-recordingStart)/1000;$('record-toggle').textContent=`■ Stop recording · ${time(seconds)}`;if(seconds>=120)stopRecording();},250);setMicUI();notify('Recording locally. It stops automatically after 2 minutes.');}catch{recorder=null;notify('This browser could not start recording. Try a current Chrome, Firefox, Edge, or Safari browser.',true);}}
$('record-toggle').onclick=startRecording;
$('clip-download').onclick=()=>{if(draft)download(draft.blob,`voice-clip-${draft.date.slice(0,10)}.${clipExtension(draft.blob)}`);};
$('clip-discard').onclick=()=>ask('Discard temporary clip?','This clip has not been saved. Download a copy first if you want to keep it.',discardDraft);
$('clip-save').onclick=async()=>{if(!draft)return;$('clip-save').disabled=true;try{await clipStore('save',{...draft,profileId:storageOwner,name:$('clip-name').value.trim().slice(0,80)||'Voice practice'});discardDraft();await renderClips();notify('Clip saved on this device.');}catch{notify('Recording storage is unavailable or full. Download the temporary clip to keep it.',true);}finally{$('clip-save').disabled=false;}};
async function renderClips(){const requestedOwner=storageOwner;clipURLs.forEach(URL.revokeObjectURL);clipURLs=[];const list=$('clips-list');list.replaceChildren();try{const clips=await clipStore('list',undefined,requestedOwner);if(storageOwner!==requestedOwner)return;if(!clips.length){const empty=el('div',undefined,'card empty');empty.append(el('h2','Your listening library starts here.'),el('p','Make a short clip in the studio. Save only the ones you want to keep.'));list.append(empty);return;}for(const clip of clips.sort((a,b)=>b.date.localeCompare(a.date))){const card=el('article',undefined,'card record-card'),heading=el('div',undefined,'cardheading'),audio=el('audio'),controls=el('div',undefined,'controls'),dl=el('button','Download'),del=el('button','Delete');const url=URL.createObjectURL(clip.blob);clipURLs.push(url);audio.src=url;audio.controls=true;audio.preload='metadata';heading.append(el('h3',clip.name),el('span',new Date(clip.date).toLocaleDateString(), 'badge'));card.append(heading,el('p',`${time(clip.duration)} · stored on this device`,'small'),audio);dl.onclick=()=>download(clip.blob,`voice-clip-${clip.date.slice(0,10)}.${clipExtension(clip.blob)}`);del.onclick=()=>ask('Delete this recording?',`“${clip.name}” will be removed from this browser. Download a copy first if you want to keep it.`,async()=>{await clipStore('delete',clip.id,requestedOwner);renderClips();notify('Recording deleted.');});controls.append(dl,del);card.append(controls);list.append(card);}}catch{list.append(el('p','Saved recording storage is unavailable. You can still record and download temporary clips.','notice'));}}
document.addEventListener('play',e=>{if(e.target.tagName==='AUDIO'){document.querySelectorAll('audio').forEach(a=>{if(a!==e.target)a.pause();});if(stream)disconnect();}},true);
function selectedRoutine(){return buildRoutine($('routine').value,Number($('session-length').value));}
function showStep(){const routine=selectedRoutine(),step=routine.steps[session?.step||0];$('step-number').textContent=`STEP ${(session?.step||0)+1} OF ${routine.steps.length}`;$('step-title').textContent=step.title;$('step-copy').textContent=step.copy;$('step-prompt').textContent=step.prompt;$('step-safety').textContent=step.safety;$('timer').textContent=time(Math.ceil(step.seconds-(session?.elapsedStep||0)));const total=routine.steps.reduce((n,s)=>n+s.seconds,0);$('session-total').textContent='Total remaining: '+time(Math.max(0,Math.ceil(total-(session?.seconds||0))));$('session-plan').textContent=`${Math.round(total/60)} minutes overall · ${routine.steps.length} guided steps, including breaks. Step timer shown below.`;}
function sessionUI(){const active=!!session;$('routine').disabled=active||!!review;$('session-length').disabled=active||!!review;$('session-start').disabled=active||!!review;$('session-pause').disabled=!active;$('session-end').disabled=!active;$('session-pause').textContent=session?.paused?'Resume':'Pause';$('session-review').hidden=!review;}
function tick(){if(!session||session.paused)return;const now=performance.now(),delta=Math.min(1.5,(now-previousTick)/1000);previousTick=now;session.elapsedStep+=delta;session.seconds+=delta;const r=selectedRoutine();if(session.elapsedStep>=r.steps[session.step].seconds){session.elapsedStep-=r.steps[session.step].seconds;session.step++;if(session.step>=r.steps.length){finishSession();return;}notify(`Next: ${r.steps[session.step].title}`);}showStep();$('session-progress').value=Math.min(100,session.seconds/r.steps.reduce((n,s)=>n+s.seconds,0)*100);}
function finishSession(){if(!session)return;clearInterval(sessionTimer);sessionTimer=null;review={id:crypto.randomUUID(),name:selectedRoutine().name,date:new Date().toISOString(),seconds:Math.round(session.seconds),pitch:summarize(session.pitch)};session=null;stopRecording();disconnect();$('comfort').value='easy';$('reflection').value='';sessionUI();notify('Practice finished. Take a rest, then save a reflection if you like.');location.hash='practice';$('comfort').focus();}
$('routine').onchange=$('session-length').onchange=()=>{showStep();$('session-progress').value=0;};
$('session-start').onclick=()=>{session={step:0,seconds:0,elapsedStep:0,paused:false,pitch:[]};previousTick=performance.now();sessionTimer=setInterval(tick,250);$('session-progress').value=0;showStep();sessionUI();notify('Practice started. Follow the prompt gently and rest between repetitions.');};
$('session-pause').onclick=()=>{if(!session)return;session.paused=!session.paused;previousTick=performance.now();sessionUI();};
$('session-end').onclick=finishSession;
$('session-save').onclick=()=>{if(!review)return;if(review.seconds<1){notify('No practice time to save. Begin a session when you are ready.');review=null;sessionUI();return;}const saved={...review,comfort:$('comfort').value,note:$('reflection').value.trim().slice(0,500)};state.sessions.push(saved);state.sessions=state.sessions.slice(-500);const stored=persist();review=null;sessionUI();showStep();renderProgress();if(stored)notify(saved.comfort==='strain'?'Practice saved. Rest your voice; seek professional guidance if discomfort persists.':'Practice saved. Showing up counts.');location.hash='progress';};
$('session-discard').onclick=()=>{review=null;sessionUI();showStep();$('session-progress').value=0;notify('Practice reflection discarded.');};
function renderProgress(){const sessions=state.sessions;$('stat-sessions').textContent=sessions.length;$('stat-minutes').textContent=Math.round(sessions.reduce((n,s)=>n+s.seconds,0)/60);$('stat-comfort').textContent=sessions.filter(s=>s.comfort==='easy').length;const list=$('sessions-list');list.replaceChildren();if(!sessions.length){list.append(el('div','Your first saved practice will appear here. Try a gentle guided session.','empty'));return;}for(const s of [...sessions].reverse()){const row=el('article',undefined,'session-row');row.append(el('h3',s.name),el('p',`${new Date(s.date).toLocaleString()} · ${time(s.seconds)} · ${s.comfort==='easy'?'Comfortable':s.comfort==='strain'?'Strain / fatigue — prioritize rest':'Still exploring'}`,'small'));if(s.pitch)row.append(el('p',`Voiced samples: median ${Math.round(s.pitch.median)} Hz · typical range ${Math.round(s.pitch.low)}–${Math.round(s.pitch.high)} Hz.`,'small'));if(s.note)row.append(el('p',s.note));list.append(row);}}
$('export-progress').onclick=()=>download(new Blob([JSON.stringify({schemaVersion:1,exportedAt:new Date().toISOString(),...state},null,2)],{type:'application/json'}),'voice-studio-progress.json');
$('delete-data').onclick=()=>ask(storageOwner==='guest'?'Delete guest practice data?':'Delete this profile’s practice data?','This removes this profile’s recordings, practice history, pitch settings, and temporary clip from this browser. Other profiles remain. Export progress and download recordings first.',async()=>{if(recorder){stopRecording();notify('Let the recording finish before deleting data.');return;}await disconnect();discardDraft();review=null;session=null;clearInterval(sessionTimer);sessionTimer=null;await accounts.clearPractice();history=[];$('session-progress').value=0;sessionUI();showStep();await renderClips();notify('Practice data deleted from this browser. Downloaded files remain on your device.');});
document.addEventListener('visibilitychange',()=>{if(document.hidden){if(session){session.paused=true;sessionUI();}document.querySelectorAll('audio').forEach(a=>a.pause());if(stream||connecting)disconnect();}else if(session?.paused)notify('Practice paused while you were away. Resume when ready; reconnect the microphone if you want feedback.');});
window.addEventListener('pagehide',()=>{generation++;stream?.getTracks().forEach(t=>t.stop());stopRecording();worker?.terminate();});
showStep();sessionUI();renderProgress();route();
accounts=initAccounts({getState:()=>state,busy:()=>!!(session||review||draft||recorder),stop:disconnect,notify,ask,setState:(next,owner,reset=true)=>{storageOwner=owner;state=next;$('range-low').value=state.settings.low;$('range-high').value=state.settings.high;$('show-range').checked=state.settings.show;renderProgress();drawChart();if(reset){history=[];renderClips();}}});
