import {readState,clipStore} from './storage.js';
import {readProfiles,saveProfiles,validTheme,mergeSessions} from './profiles-store.js';
const $=id=>document.getElementById(id),key=id=>`voice-studio-v1:${id}`;
export function initAccounts(hooks){
 let profiles=readProfiles(localStorage),owner='guest',running=false,applying=false;
 let guestTheme=validTheme(document.documentElement.dataset.theme);
 try{guestTheme=validTheme(localStorage.getItem('voice-studio-guest-theme')||guestTheme);
 // Retain any practice already cached by the previous account version, without contacting its server.
 for(let n=0;n<localStorage.length&&profiles.length<50;n++){const k=localStorage.key(n);if(!k.startsWith('voice-studio-v1:'))continue;const id=k.slice(16);if(!/^[a-zA-Z0-9-]{1,80}$/.test(id)||profiles.some(p=>p.id===id))continue;let cached;try{cached=JSON.parse(localStorage.getItem(k));}catch{continue;}if(cached?.profile)profiles.push({id,name:String(cached.profile.display_name||'Recovered profile').slice(0,60),goal:String(cached.profile.goal||'').slice(0,300),theme:validTheme(cached.profile.preferences?.theme)});}
 saveProfiles(localStorage,profiles);localStorage.removeItem('voice-studio-auth');sessionStorage.removeItem('voice-studio-auth');
 }catch{hooks.notify('Browser storage is unavailable. Guest practice still works; export progress before closing.',true);}
 const current=()=>profiles.find(p=>p.id===owner);
 const status=(message,error=false)=>{$('account-status').textContent=message;$('account-status').classList.toggle('error',error);};
 function paint(){const select=$('profile-select');select.replaceChildren(new Option('Guest', 'guest'));for(const p of profiles)select.add(new Option(p.name,p.id));select.value=owner;select.disabled=running;$('profile-details').hidden=owner==='guest';const p=current();if(p){$('profile-name').value=p.name;$('profile-goal').value=p.goal;}$('profile-badge').textContent=p?.name||'Guest';$('space-label').textContent=p?`${p.name}’S PRACTICE SPACE`:'YOUR PRACTICE SPACE';$('delete-data').textContent=p?'Delete this profile’s practice data':'Delete guest data from this device';}
 function ready(){if(running)return false;if(hooks.busy()){hooks.notify('Finish your session and save or discard your temporary clip before changing profiles.',true);return false;}return true;}
 function changed(){if(applying)return;try{if(owner==='guest'){guestTheme=validTheme(document.documentElement.dataset.theme);localStorage.setItem('voice-studio-guest-theme',guestTheme);localStorage.setItem('voice-studio-v1',JSON.stringify(hooks.getState()));}else{const p=current();if(!p)throw Error();p.theme=validTheme(document.documentElement.dataset.theme);localStorage.setItem(key(owner),JSON.stringify(hooks.getState()));saveProfiles(localStorage,profiles);}status('Saved privately in this browser.');return true;}catch{status('Could not save on this device. Export progress before closing.',true);return false;}}
 async function switchTo(id,save=true){if(!ready()){paint();return;}if(id!=='guest'&&!profiles.some(p=>p.id===id)){paint();return;}if(save&&!changed()){paint();return;}running=true;$('main').inert=true;try{await hooks.stop();owner=id;const next=readState({getItem:()=>localStorage.getItem(id==='guest'?'voice-studio-v1':key(id))});hooks.setState(next,id);applying=true;window.dispatchEvent(new CustomEvent('voice-theme-apply',{detail:current()?.theme||guestTheme}));applying=false;try{localStorage.setItem('voice-studio-active-profile',id);}catch{}status('This profile stays on this device.');}finally{running=false;$('main').inert=false;paint();}}
 $('profile-select').onchange=()=>switchTo($('profile-select').value);
 $('profile-create-form').onsubmit=async e=>{e.preventDefault();if(!ready())return;if(profiles.length>=50){status('This browser can hold up to 50 profiles.',true);return;}const name=$('new-profile-name').value.trim();if(!name)return;const p={id:crypto.randomUUID(),name:name.slice(0,60),goal:'',theme:validTheme(document.documentElement.dataset.theme)};try{localStorage.setItem(key(p.id),JSON.stringify({settings:{low:160,high:220,show:true},sessions:[]}));saveProfiles(localStorage,[...profiles,p]);profiles.push(p);$('new-profile-name').value='';await switchTo(p.id);}catch{status('Could not create a profile. Browser storage may be blocked or full.',true);}};
 $('profile-form').onsubmit=e=>{e.preventDefault();const p=current();if(!p)return;const previous={...p};p.name=$('profile-name').value.trim().slice(0,60)||'Voice explorer';p.goal=$('profile-goal').value.trim().slice(0,300);try{saveProfiles(localStorage,profiles);paint();status('Profile saved on this device.');}catch{Object.assign(p,previous);status('Could not save your profile.',true);}};
 $('profile-guest').onclick=()=>switchTo('guest');
 $('import-guest').onclick=()=>{if(!ready())return;hooks.ask('Copy guest practice into this profile?','Copies this browser’s guest history into the selected profile. Guest history stays available. Recordings remain in their original profile.',()=>{const state=hooks.getState();hooks.setState({...state,sessions:mergeSessions(state.sessions,readState(localStorage).sessions)},owner,false);changed();});};
 $('profile-delete').onclick=()=>{if(!ready())return;const p=current();if(!p)return;hooks.ask('Delete this local profile?',`This removes “${p.name}”, its practice history, preferences, and recordings from this browser. Export progress and download recordings first if you want to keep them.`,async()=>{if(!ready())return;await clipStore('clear',undefined,p.id);const next=profiles.filter(item=>item.id!==p.id);saveProfiles(localStorage,next);profiles=next;localStorage.removeItem(key(p.id));localStorage.removeItem(`voice-studio-pending:${p.id}`);await switchTo('guest',false);status('Profile deleted from this browser.');});};
 window.addEventListener('voice-theme-change',changed);
 paint();let selected='guest';try{selected=localStorage.getItem('voice-studio-active-profile')||'guest';}catch{}if(selected!=='guest')switchTo(selected,false);
 return {changed,get owner(){return owner;},get loading(){return running;},async clearPractice(){await clipStore('clear',undefined,owner);hooks.setState({settings:{low:160,high:220,show:true},sessions:[]},owner);if(!changed())throw Error('Could not save cleared practice.');}};
}
