/* Development-only local profile integration fixture; no physical mic or network. */
window.addEventListener('DOMContentLoaded',()=>{
 const out=document.createElement('section');out.id='account-test-results';out.className='card';document.querySelector('main').prepend(out);const start=document.createElement('button');start.textContent='Run profile checks';out.append(start);
 start.onclick=async()=>{start.disabled=true;const $=id=>document.getElementById(id),wait=ms=>new Promise(r=>setTimeout(r,ms)),keys=['voice-studio-profiles','voice-studio-active-profile','voice-studio-theme','voice-studio-guest-theme'],backup=new Map(keys.map(k=>[k,localStorage.getItem(k)]));let a,b,clip;let count=0;const {clipStore}=await import('../storage.js');
 const check=(ok,label)=>{const p=document.createElement('p');p.textContent=(ok?'PASS: ':'FAIL: ')+label;out.append(p);if(!ok)throw Error(label);count++;};
 const until=async fn=>{for(let n=0;n<50;n++){if(fn())return;await wait(100);}throw Error('Timed out');};
 async function create(name){$('new-profile-name').value=name;$('profile-create-form').requestSubmit();await until(()=>$('profile-badge').textContent===name);return $('profile-select').value;}
 async function select(id){$('profile-select').value=id;$('profile-select').dispatchEvent(new Event('change'));await until(()=>$('profile-select').value===id&&!$('main').inert);}
 try{
 location.hash='account';a=await create('Local A');check(a!=='guest','Create profile without email or sign-in');$('profile-goal').value='Easy speech';$('profile-form').requestSubmit();check(JSON.parse(localStorage.getItem('voice-studio-profiles')).find(p=>p.id===a).goal==='Easy speech','Profile metadata persists');
 await wait(100);check(!$('settings').hidden,'Legacy profile links open the Settings page');check(document.querySelectorAll('[name="theme-palette"]').length===15,'Settings offers 15 visual palettes');document.querySelector('[name="theme-palette"][value="nonbinary"]').click();document.querySelector('[name="theme-tone"][value="dark"]').click();check(document.documentElement.dataset.theme==='nonbinary-dark','Visual palette and brightness controls apply the selected theme');$('range-low').value='100';$('range-high').value='180';$('range-form').requestSubmit();check(JSON.parse(localStorage.getItem('voice-studio-v1:'+a)).settings.low===100,'Pitch preferences save under the profile owner');
 location.hash='practice';$('session-length').value='60';$('session-length').dispatchEvent(new Event('change'));check($('session-total').textContent.includes('60:00'),'Hour practice remains available');$('session-start').click();await wait(1100);$('session-end').click();$('reflection').value='Only profile A';$('session-save').click();check(JSON.parse(localStorage.getItem('voice-studio-v1:'+a)).sessions.length===1,'Practice history saves to the active profile');
 clip=crypto.randomUUID();await clipStore('save',{id:clip,profileId:a,name:'Local A recording',date:new Date().toISOString(),duration:1,blob:new Blob(['test'],{type:'audio/webm'})});location.hash='account';b=await create('Local B');check(!$('sessions-list').textContent.includes('Only profile A')&&$('profile-goal').value===''&&$('range-low').value==='160','Second profile has separate history, goal, and pitch range');check((await clipStore('list',undefined,b)).every(c=>c.id!==clip),'Second profile excludes first profile recordings');await select(a);check($('profile-goal').value==='Easy speech'&&$('sessions-list').textContent.includes('Only profile A')&&$('range-low').value==='100'&&document.documentElement.dataset.theme==='nonbinary-dark','Switching back restores profile preferences and history');check((await clipStore('list',undefined,a)).some(c=>c.id===clip),'First profile retains its recording');check(localStorage.getItem('voice-studio-active-profile')===a,'Profile selection persists for reload');await select('guest');check(!$('sessions-list').textContent.includes('Only profile A'),'Guest practice remains separate');await select(b);$('profile-delete').click();$('confirm-ok').click();await until(()=>$('profile-select').value==='guest');check(!JSON.parse(localStorage.getItem('voice-studio-profiles')).some(p=>p.id===b)&&JSON.parse(localStorage.getItem('voice-studio-v1:'+a)).sessions.length===1,'Deleting one profile preserves another profile’s history');
 out.prepend(Object.assign(document.createElement('h2'),{textContent:count+' profile checks passed'}));
 }catch(e){out.prepend(Object.assign(document.createElement('h2'),{textContent:'Profile check failed: '+e.message}));}
 finally{if(a){await clipStore('clear',undefined,a);localStorage.removeItem('voice-studio-v1:'+a);}if(b)localStorage.removeItem('voice-studio-v1:'+b);for(const[k,v]of backup){if(v===null)localStorage.removeItem(k);else localStorage.setItem(k,v);}}
 };
});
