import {test} from 'node:test';
import assert from 'node:assert/strict';
import {validateBackup,makeBackup,restoreBackup} from '../backup-data.js';
const profile=()=>({name:'Spencer',goal:'Easy practice',theme:'ocean-dark',language:{tagline:'My voice, my pace',pronouns:{subject:'she / they',object:'them',possessive:'theirs'}},state:{settings:{low:140,high:190,show:false},sessions:[{id:'session',name:'Practice',date:'2026-10-02T12:00:00Z',seconds:60,comfort:'easy',note:'Private',pitch:{median:170,low:160,high:180}}]},clips:[{name:'Sample',date:'2026-10-02T12:00:00Z',duration:2,type:'audio/webm;codecs=opus',audio:'YWJj'}]});
const backup=()=>({format:'true-you-voice-backup',version:1,profiles:[profile()]});
function fixture(){const map=new Map([['voice-studio-profiles',JSON.stringify([{id:'existing',name:'Existing',theme:'forest-light'}])],['voice-studio-v1:existing','keep']]),clips=new Map();let next=0;return {map,clips,options:{storage:{getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)},saveClips:async values=>{for(const c of values)clips.set(c.id,c);},removeClips:async ids=>{for(const id of ids)clips.delete(id);},decode:(audio,type)=>new Blob([Buffer.from(audio,'base64')],{type}),uuid:()=>`new-${++next}`}};}
test('full backup preserves wording, pitch, history and audio',async()=>{const source=profile();const b=await makeBackup([{...source,id:'source'}],async id=>{assert.equal(id,'source');return [{...source.clips[0],blob:new Blob(['abc'],{type:'audio/webm;codecs=opus'})}];},async blob=>Buffer.from(await blob.arrayBuffer()).toString('base64'));assert.deepEqual(b.profiles,validateBackup(backup()).profiles);});
test('restore creates distinct owners and keeps existing profile data',async()=>{const f=fixture();const restored=await restoreBackup(backup(),f.options);assert.equal(restored[0].id,'new-1');assert.equal(f.map.get('voice-studio-v1:existing'),'keep');assert.equal(JSON.parse(f.map.get('voice-studio-profiles')).length,2);assert.equal(f.clips.get('new-2').profileId,'new-1');assert.equal(await f.clips.get('new-2').blob.text(),'abc');assert.equal(JSON.parse(f.map.get('voice-studio-v1:new-1')).sessions[0].note,'Private');});
test('repeated restore makes independent copies',async()=>{const f=fixture();await restoreBackup(backup(),f.options);await restoreBackup(backup(),f.options);assert.equal(JSON.parse(f.map.get('voice-studio-profiles')).length,3);assert.equal(f.clips.size,2);});
test('rejects unsupported, incomplete and malformed backups',()=>{for(const value of [{},{...backup(),version:2},{...backup(),profiles:[]},{...backup(),profiles:[{...profile(),state:{}}]}])assert.throws(()=>validateBackup(value));for(const patch of [{audio:'<script>'},{type:'text/html'},{duration:500},{date:'bad'}])assert.throws(()=>validateBackup({...backup(),profiles:[{...profile(),clips:[{...profile().clips[0],...patch}]}]}));});
test('rejects corrupted sessions rather than silently dropping practice',()=>{const p=profile();p.state.sessions[0].seconds=-1;assert.throws(()=>validateBackup({...backup(),profiles:[p]}),/history/);});
test('metadata is bounded, untrusted extra fields are discarded',()=>{const p=profile();p.name='x'.repeat(300);p.state.sessions[0].attack='<script>';const b=validateBackup({...backup(),profiles:[p]});assert.equal(b.profiles[0].name.length,60);assert.equal(b.profiles[0].state.sessions[0].attack,undefined);});
test('storage failure rolls back imported audio and state',async()=>{const f=fixture(),original=f.map.get('voice-studio-profiles');const set=f.options.storage.setItem;f.options.storage.setItem=(k,v)=>{if(k==='voice-studio-profiles')throw Error('quota');set(k,v);};await assert.rejects(restoreBackup(backup(),f.options),/Storage may be blocked or full/);assert.equal(f.map.get('voice-studio-profiles'),original);assert.equal(f.clips.size,0);assert.equal(f.map.has('voice-studio-v1:new-1'),false);});
test('profile capacity errors leave storage unchanged',async()=>{const f=fixture();f.map.set('voice-studio-profiles',JSON.stringify(Array.from({length:50},(_,i)=>({id:'p'+i,name:'Profile'}))));await assert.rejects(restoreBackup(backup(),f.options),/room for 0/);assert.equal(f.clips.size,0);});
test('profile added by another tab during restore is preserved',async()=>{const f=fixture(),save=f.options.saveClips;f.options.saveClips=async clips=>{await save(clips);const current=JSON.parse(f.map.get('voice-studio-profiles'));f.map.set('voice-studio-profiles',JSON.stringify([...current,{id:'other-tab',name:'Other tab'}]));};await restoreBackup(backup(),f.options);assert.equal(JSON.parse(f.map.get('voice-studio-profiles')).length,3);});
test('profile-only restore works without recording storage',async()=>{const f=fixture(),b=backup();b.profiles[0].clips=[];f.options.saveClips=async()=>{throw Error('IndexedDB unavailable');};await restoreBackup(b,f.options);assert.equal(JSON.parse(f.map.get('voice-studio-profiles')).length,2);});
