import {test} from 'node:test';
import assert from 'node:assert/strict';
import {CloudClient,validateConfig,mergeSessions} from '../cloud.js';
import {buildRoutine,sessionLengths} from '../routines.js';
const config={url:'https://example.supabase.co',publicKey:'sb_publishable_test'};
function storage(){const m=new Map();return {getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)};}
const response=(data,status=200)=>({ok:status<400,status,text:async()=>data===null?'':JSON.stringify(data)});
test('client rejects secret keys and unsafe service URLs',()=>{assert.equal(validateConfig({url:'',publicKey:''}),false);assert.throws(()=>validateConfig({...config,publicKey:'sb_secret_do_not_expose'}));assert.throws(()=>validateConfig({...config,url:'https://evil.example'}));});
test('email verification stores only a tab session by default',async()=>{const tab=storage(),remember=storage(),requests=[];const client=new CloudClient(config,{tabStorage:tab,rememberStorage:remember,fetch:async(url,opts)=>{requests.push({url,opts});return url.endsWith('/otp')?response({}):response({access_token:'test-jwt',refresh_token:'test-refresh',expires_in:3600,user:{id:'user-a',email:'test@example.invalid'}});}});await client.sendCode('test@example.invalid');await client.verifyCode('test@example.invalid','123456',false);assert.equal(client.user.id,'user-a');assert.ok(tab.getItem('voice-studio-auth'));assert.equal(remember.getItem('voice-studio-auth'),null);assert.equal(JSON.parse(requests[0].opts.body).create_user,true);assert.equal(JSON.parse(requests[1].opts.body).type,'email');assert.equal(requests[0].opts.credentials,'omit');});
test('parallel requests share one refresh; metadata cannot change the owner',async()=>{let refreshes=0,body;const client=new CloudClient(config,{tabStorage:storage(),rememberStorage:storage(),fetch:async(url,opts)=>{if(url.includes('/token?')){refreshes++;return response({access_token:'fresh',refresh_token:'fresh-refresh',expires_in:3600,user:{id:'user-a'}});}body=opts.body;assert.equal(opts.headers.Authorization,'Bearer fresh');return response(null);}});client.auth={access_token:'expired',refresh_token:'old',expires_at:0,user:{id:'user-a'}};await Promise.all([client.accessToken(),client.accessToken()]);assert.equal(refreshes,1);await client.saveProfile({user_id:'user-b',display_name:'A'});assert.equal(JSON.parse(body).user_id,'user-a');});
test('refresh failure clears invalid credentials but network failure preserves them',async()=>{const client=new CloudClient(config,{tabStorage:storage(),rememberStorage:storage(),fetch:async()=>response({msg:'Expired'},400)});client.auth={access_token:'expired',refresh_token:'old',expires_at:0,user:{id:'user-a'}};await assert.rejects(client.accessToken());assert.equal(client.user,null);client.fetch=async()=>{throw new Error('offline');};client.auth={access_token:'expired',refresh_token:'old',expires_at:0,user:{id:'user-a'}};await assert.rejects(client.accessToken());assert.equal(client.user.id,'user-a');});
test('sign-out clears local credentials even offline',async()=>{const tab=storage(),remember=storage(),client=new CloudClient(config,{tabStorage:tab,rememberStorage:remember,fetch:async()=>{throw new Error('offline');}});client.saveAuth({access_token:'token',refresh_token:'refresh',expires_at:Date.now()/1000+3600,user:{id:'a'}},true);await assert.rejects(client.signOut());assert.equal(client.user,null);assert.equal(remember.getItem('voice-studio-auth'),null);});
test('session merging deduplicates by ID without deleting other-device sessions',()=>{assert.deepEqual(mergeSessions([{id:'a',date:'2026-01-01'},{id:'b',date:'2026-01-02'}],[{id:'a',date:'2026-01-01',note:'local'}]),[{id:'a',date:'2026-01-01',note:'local'},{id:'b',date:'2026-01-02'}]);});
for(const key of ['daily','warmup','resonance'])for(const minutes of sessionLengths)test(`${key}: ${minutes} minute block has exact timing and silent breaks`,()=>{const plan=buildRoutine(key,minutes);assert.equal(plan.steps.reduce((n,s)=>n+s.seconds,0),minutes*60);assert.ok(plan.steps.every(s=>s.seconds>0&&s.seconds<=120));const silent=plan.steps.filter(s=>/break|Listen|Arrive/.test(s.title)).reduce((n,s)=>n+s.seconds,0);assert.ok(silent>minutes*60*.5);assert.equal(plan.steps.at(-1).title,'Return to easy speech');});
