/* Local development fixture: disposable profiles, synthetic audio, no uploads. */
window.addEventListener('DOMContentLoaded',()=>{
 const $=id=>document.getElementById(id),out=document.createElement('section');out.id='launch-results';out.className='card';document.querySelector('main').prepend(out);const button=document.createElement('button');button.textContent='Run launch checks';out.append(button);
 button.onclick=async()=>{
  button.disabled=true;let count=0;const before=new Map(Array.from({length:localStorage.length},(_,i)=>{const k=localStorage.key(i);return [k,localStorage.getItem(k)];}));const originalClick=HTMLAnchorElement.prototype.click,originalURL=URL.createObjectURL;let exported;
  const {clipStore}=await import('../storage.js');const {validateBackup}=await import('../backup-data.js');const originalOwners=JSON.parse(before.get('voice-studio-profiles')||'[]').map(p=>p.id);const cleanOwners=new Set();
  const wait=ms=>new Promise(r=>setTimeout(r,ms));const until=async condition=>{for(let i=0;i<100;i++){if(condition())return;await wait(50);}throw Error('Timed out');};
  const check=(value,label)=>{const p=document.createElement('p');p.textContent=(value?'PASS: ':'FAIL: ')+label;out.append(p);if(!value)throw Error(label);count++;};
  const choose=async data=>{const transfer=new DataTransfer();transfer.items.add(new File([JSON.stringify(data)],'backup.json',{type:'application/json'}));$('backup-file').files=transfer.files;$('backup-file').dispatchEvent(new Event('change'));await until(()=>!$('main').inert);};
  try{
   location.hash='settings';await wait(100);$('welcome-open').click();check($('welcome-dialog').open&&document.activeElement.id==='welcome-close','Welcome dialog opens with keyboard focus');$('welcome-profile').click();check(!$('welcome-dialog').open&&document.activeElement.id==='new-profile-name','Welcome routes to profile creation');
   $('new-profile-name').value='Backup fixture';$('profile-create-form').requestSubmit();await until(()=>$('profile-badge').textContent==='Backup fixture');const owner=$('profile-select').value;cleanOwners.add(owner);
   $('practice-tagline').value='My private wording';$('pronoun-subject').value='they';$('language-form').requestSubmit();$('range-low').value=145;$('range-high').value=195;$('range-form').requestSubmit();
   const frames=4000,bytes=new ArrayBuffer(44+frames*2),view=new DataView(bytes),write=(offset,s)=>[...s].forEach((c,i)=>view.setUint8(offset+i,c.charCodeAt(0)));write(0,'RIFF');view.setUint32(4,36+frames*2,true);write(8,'WAVE');write(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,8000,true);view.setUint32(28,16000,true);view.setUint16(32,2,true);view.setUint16(34,16,true);write(36,'data');view.setUint32(40,frames*2,true);for(let i=0;i<frames;i++)view.setInt16(44+i*2,Math.sin(i*2*Math.PI*180/8000)*5000,true);
   await clipStore('save',{id:crypto.randomUUID(),profileId:owner,name:'Synthetic sample',date:new Date().toISOString(),duration:.5,blob:new Blob([bytes],{type:'audio/wav'})});
   HTMLAnchorElement.prototype.click=function(){if(!this.download)return originalClick.call(this);};URL.createObjectURL=function(blob){if(blob.type==='application/json')exported=blob;return originalURL.call(URL,blob);};
   $('backup-download').click();await until(()=>!!exported&&!$('main').inert);const archive=validateBackup(JSON.parse(await exported.text()));check(archive.profiles.length===1&&archive.profiles[0].language.tagline==='My private wording'&&archive.profiles[0].state.settings.low===145&&archive.profiles[0].clips.length===1,'Current profile backup includes preferences, wording and recording');
   check(!$('backup-save').hidden&&$('backup-save').href.startsWith('blob:')&&$('backup-save').download==='true-you-voice-backup.json'&&document.activeElement.id==='backup-save','Prepared backup has a persistent save link and keyboard focus');
   exported=null;$('backup-audio').checked=false;$('backup-download').click();await until(()=>!!exported&&!$('main').inert);check(JSON.parse(await exported.text()).profiles[0].clips.length===0,'Recordings can be omitted');$('backup-audio').checked=true;
   exported=null;$('backup-scope').value='all';$('backup-download').click();await until(()=>!!exported&&!$('main').inert);check(JSON.parse(await exported.text()).profiles.length>=2,'All-profile backup includes guest and named profiles');
   await choose(archive);check($('restore-dialog').open&&$('restore-summary').textContent.includes('1 recording(s)'),'Restore validates file and previews contents');$('restore-confirm').click();await until(()=>$('backup-status').textContent.startsWith('Backup restored')&&!$('main').inert);const registry=JSON.parse(localStorage.getItem('voice-studio-profiles'));const restored=registry.find(p=>p.id!==owner&&!originalOwners.includes(p.id));cleanOwners.add(restored.id);check(registry.some(p=>p.id===owner)&&restored.name==='Backup fixture','Restore keeps original profile and adds a separate copy');
   const [clip]=await clipStore('list',undefined,restored.id);const audio=new AudioContext();const decoded=await audio.decodeAudioData(await clip.blob.arrayBuffer());await audio.close();check(decoded.duration===.5,'Restored recording decodes as playable audio');
   $('profile-select').value=restored.id;$('profile-select').dispatchEvent(new Event('change'));await until(()=>$('range-low').value==='145'&&!$('main').inert);check($('studio-tagline').textContent==='My private wording','Restored profile preferences and wording render in the app');
   await choose({format:'bad'});check(!$('restore-dialog').open&&$('backup-status').textContent.includes('full backup'),'Invalid backups produce a clear error without opening restore');
   await choose({...archive,profiles:[...archive.profiles,{...archive.profiles[0],name:'Second profile'}]});$('restore-selection').value='1';$('restore-selection').dispatchEvent(new Event('change'));check($('restore-summary').textContent.startsWith('1 profile(s)'),'A single profile can be selected from an archive');$('restore-cancel').click();check(!$('restore-dialog').open,'Restore cancellation leaves data in place');
   location.hash='practice';$('session-start').click();$('backup-download').click();check($('backup-status').textContent.includes('finish your session'),'Backups are blocked during active practice');$('session-end').click();$('session-discard').click();
   check($('welcome-open').textContent==='Getting started'&&document.querySelector('footer a[href*="issues/new"]').rel.includes('noopener'),'Help and public feedback remain accessible');
   const frame=document.createElement('iframe');frame.title='Narrow layout fixture';frame.style.cssText='width:375px;height:812px;max-width:none;border:0';const loaded=new Promise(resolve=>frame.onload=resolve);frame.src='/#settings';out.append(frame);await loaded;await wait(500);const doc=frame.contentDocument;check(doc.documentElement.scrollWidth<=doc.documentElement.clientWidth,'Settings layout fits a 375px viewport without horizontal overflow');doc.getElementById('welcome-open').click();const dialog=doc.getElementById('welcome-dialog');check(dialog.open&&dialog.getBoundingClientRect().width<=375&&dialog.clientHeight<=812,'Welcome guide fits a narrow viewport and remains scrollable');frame.remove();
   const duplicate=crypto.randomUUID(),trial=crypto.randomUUID();let rejected=false;try{await clipStore('saveMany',[{id:trial,profileId:owner,blob:new Blob(['trial'])},{id:duplicate,profileId:owner,blob:new Blob(['first'])},{id:duplicate,profileId:owner,blob:new Blob(['second'])}]);}catch{rejected=true;}check(rejected&&!(await clipStore('list',undefined,owner)).some(c=>c.id===trial),'Recording batch failure rolls back the full IndexedDB transaction');
   out.append(document.createTextNode(`Complete: ${count} checks passed.`));
  }catch(e){out.append(document.createTextNode('FAILED: '+e.message));}
  finally{
   HTMLAnchorElement.prototype.click=originalClick;URL.createObjectURL=originalURL;
   for(const owner of cleanOwners)await clipStore('clear',undefined,owner);
   for(const k of Array.from({length:localStorage.length},(_,i)=>localStorage.key(i)))if(k.startsWith('voice-studio-')||k==='true-you-voice-welcome-v1')localStorage.removeItem(k);
   for(const [k,v] of before)localStorage.setItem(k,v);
  }
 };
});
