import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readProfiles,saveProfiles,validTheme,mergeSessions} from '../profiles-store.js';
test('profile registry rejects malformed records and deduplicates owners',()=>{const read=value=>readProfiles({getItem:()=>JSON.stringify(value)});assert.deepEqual(read({}),[]);assert.deepEqual(read([{id:'guest',name:'No'},{id:'bad:id',name:'No'},{id:'a',name:' A ',goal:'x',theme:'nonbinary-dark'},{id:'a',name:'duplicate'},{id:'b',name:''}]),[{id:'a',name:'A',goal:'x',theme:'nonbinary-dark',language:{tagline:'Practice a feminine voice with curiosity, comfort, and a little consistency.',pronouns:{subject:'',object:'',possessive:''}}}]);assert.deepEqual(readProfiles({getItem:()=>{throw Error('blocked');}}),[]);});
test('profile metadata is bounded and themes validated',()=>{const [p]=readProfiles({getItem:()=>JSON.stringify([{id:'a',name:'x'.repeat(100),goal:'x'.repeat(500),theme:'bad'}])});assert.equal(p.name.length,60);assert.equal(p.goal.length,300);assert.equal(p.theme,'trans-fem-dark');assert.equal(validTheme('trans-masc-dark'),'trans-fem-dark');});
test('storage failures are surfaced instead of reporting a saved profile',()=>{assert.throws(()=>saveProfiles({setItem:()=>{throw Error('full');}},[{id:'a',name:'A'}]),/full/);});
test('guest copying deduplicates sessions and retains profile history',()=>{assert.deepEqual(mergeSessions([{id:'a',date:'2026-01-01'},{id:'b',date:'2026-01-02'}],[{id:'a',date:'2026-01-01'}]).map(s=>s.id),['a','b']);});
test('all color-friendly choices survive profile storage validation',()=>{for(const theme of ['blue-gold-light','blue-gold-dark','teal-rose-light','teal-rose-dark','monochrome-light','monochrome-dark']){assert.equal(readProfiles({getItem:()=>JSON.stringify([{id:'a',name:'A',theme}])})[0].theme,theme);}});
test('nature, additional Pride, and high contrast themes persist per profile',()=>{for(const palette of ['ocean','forest','sunset','bisexual','lesbian','pansexual','asexual','rainbow','high-contrast'])for(const mode of ['light','dark']){const theme=palette+'-'+mode;assert.equal(readProfiles({getItem:()=>JSON.stringify([{id:'a',name:'A',theme}])})[0].theme,theme);}});
